# Generated by Django 3.2.7 on 2021-09-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_cardapio_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='preço',
            new_name='preco',
        ),
    ]
