# Generated by Django 3.2.7 on 2021-10-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PratoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadee', models.IntegerField(blank=True, null=True)),
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prato.prato')),
            ],
        ),
    ]
