# Generated by Django 3.2.7 on 2021-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prato', '0002_pratopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pratopedido',
            name='nome',
        ),
        migrations.AddField(
            model_name='pratopedido',
            name='nome',
            field=models.ManyToManyField(to='prato.Prato'),
        ),
    ]
