# Generated by Django 3.2.7 on 2021-10-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_pratos'),
        ('prato', '0003_auto_20211015_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PratoPedido',
        ),
    ]
