# Generated by Django 3.2.7 on 2021-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('mesa', models.IntegerField()),
                ('prato', models.ManyToManyField(to='prato.Prato')),
            ],
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('local', models.CharField(max_length=100)),
                ('prato', models.ManyToManyField(to='prato.Prato')),
            ],
        ),
    ]
