# Generated by Django 3.2.7 on 2021-10-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliver',
            old_name='prato',
            new_name='pratos',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='prato',
            new_name='pratos',
        ),
    ]
