# Generated by Django 3.2.7 on 2021-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20211013_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
