# Generated by Django 3.2.7 on 2021-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prato', '0003_auto_20211015_1249'),
        ('pedido', '0004_alter_pedido_pratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pratos',
            field=models.ManyToManyField(to='prato.Prato'),
        ),
    ]
