# Generated by Django 3.2.7 on 2021-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_pratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='observacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
